added channel_id to PushMessage for new Android Notification Channels
expo-community/expo-server-sdk-python pull request #13
Opened 2018-06-20 14:34 UTC by earle

2018-06-21 00:46 UTC, anp commented
Hi! Thanks for sending this over! I've added @ccheever as a reviewer on this, he should be able to take a look soon.

2018-06-21 03:08 UTC, ide requested changes

2018-06-21 03:08 UTC, ide commented on exponent_server_sdk/__init__.py
> +            payload['channel_id'] = self.channel_id
The field in the JSON-encoded payload sent to the server should be channelId instead of channel_id

2018-07-04 04:34 UTC, raphaelrk commented
Fixed the channel_id vs channelId issue in #14

2018-07-13 22:46 UTC, wli commented
closing in favor of #14. Thanks for the contribution regardless!

2018-07-13 22:46 UTC, closed without merging